### ISSUE TITLE
Using Frame SRL

### ISSUE THREAD

**Issue by beneyal** [microth/PathLSTM#17]
Hello,

I didn't really understand how to use the `parse.sh` script for FrameNet SRL. I've all the models and libraries, including BISTparser and NLP4J, and FrameNet 1.5 (downloaded using NLTK).

From here, I'm pretty lost. How to retrain BISTparser and NLP4J using the 10-fold jackknifing, to recreate your results? Do I even have to do that?

Sorry if it's a newbie question, thank your for your time!

**Comment by microth** [comment]
For my experiments with FrameNet, as published at ICCG 2016, I simply trained BISTparser on a dependency-converted version of OntoNotes 5.0 (FN has no gold syntax trees, so you can't do 10-fold jackknifing). I then applied the trained model, plus the POS tagger from NLP4J, to the full FrameNet data set. If you replicate these steps and convert the output into the CoNLL-2009 format, the class Parse (instead of CompletePipeline) from PathLSTM can be used to directly apply the SRL model to the syntactically preprocessed data.

Easier option: drop me an email and I'll send you a copy of the preprocessed test corpus.

Hope this helps.
